"""R22 workload and schedule (version 2 of the R21 table): the same frozen sample, stage and observed per-task rates as
R21-WORKLOAD.json (every in-scope page; price unknown; no dollar amount), corrected as Review 22 asked:
  * the schedule is GENERATED by simulating the implemented whole-project reservation rule (schedule_sim.simulate, the
    rule arm_ev.py v4 applies) on the staged manifest, with the rolling 60 / project, the A base's usage, the 12 / document
    durable cap and the frozen arm order -- under the worst-case demand and under the expected demand, with A's usage
    either aged out or spent at the start; elapsed time is reported in hours (never rounded into 'days');
  * the p90-based token figures are labelled ESTIMATES (p90 of observed per-task input incl. cached, times counts), not bounds;
  * three request figures are kept apart: the EXPECTED workload, the PROPOSED authorized maximum (the caps; 688 only if
    approved; not approved by this package) and the UNCAPPED structural maximum (12 x PDFs x 4 arms + A);
  * the reader's own per-reading constant (8: a single reading stops at 8 charged reads, plus the reads of the page in
    progress) is recorded beside the durable 12; the durable cap is what a document can reach across a resume.
Writes review22/workload/R22-WORKLOAD.json."""
import collections
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import schedule_sim  # noqa: E402

R21 = pathlib.Path("C:/t/iso/work/r2x/review21")
R = HERE.parent
stage = json.loads(pathlib.Path("C:/t/r2x/r21-stage/R21-STAGE.json").read_text(encoding="utf-8"))["files"]
classes = json.loads((R21 / "R21-PAGE-CLASSES.json").read_text(encoding="utf-8"))["pages"]
obs = json.loads(pathlib.Path("C:/t/iso/work/r2x/review20/workload/OBSERVED-WORKLOAD.json").read_text(encoding="utf-8"))["tasks"]
prev = json.loads((R21 / "workload/R21-WORKLOAD.json").read_text(encoding="utf-8"))
MAX_PAGES, DOC_CAP, READER_PER_READING, ESC_CAP, DAY = 4, 12, 8, 2, 60
ARMS = ["L1", "L2", "L3", "L4"]
by_doc = collections.defaultdict(list)
for p in classes:
    by_doc[p["doc_key"]].append(p)
T = {k: obs[k] for k in ("discover_page", "discover_region", "read_identity", "read_revision", "read_decision", "read_field_context", "read_submittal_form")}
tok = lambda k, q="mean": (T[k]["input_total_incl_cached"][q] or 0)
out_tok = lambda k: T[k]["output"]["mean"] or 0
lat = lambda k: (T[k]["latency_ms"]["p50"] or 0) / 1000
EXP = prev["assumptions"]["expected_reads_per_triggered_page"]        # unchanged assumptions (every in-scope page triggered)
rows, per_project, totals = [], collections.defaultdict(lambda: collections.defaultdict(float)), collections.defaultdict(lambda: collections.defaultdict(float))
projects, demand_exp, demand_worst, seconds_exp = collections.defaultdict(list), {}, {}, collections.defaultdict(float)
for f in stage:
    ep = f["doc_key"].split("/")[0][3:]
    pages = [p for p in by_doc.get(f["doc_key"], []) if p["in_scope"]]
    if f["extension"] != ".pdf":
        rows.append({"doc": f["doc_key"], "ep": ep, "role": f["role"], "pages_in_scope": 0, "pages_beyond_scope": 0, "shape": "unsupported_input", "per_arm": {}})
        continue
    projects[ep].append(f["doc_key"])
    n_in, n_beyond = len(pages), (f["pages"] or 0) - len(pages)
    per_arm = {}
    for arm in ARMS:
        roi, x = arm in ("L2", "L4"), arm in ("L3", "L4")
        req = n_in * (EXP["discovery"] + EXP["read_identity"] + EXP["read_revision"] + EXP["read_decision"]) + (n_in * EXP["targeted"] if x else 0)
        req = min(req, DOC_CAP)
        disc = lambda q="mean": sum((tok("discover_region", q) if (roi and p["size"] == "drawing_sheet") else tok("discover_page", q)) for p in pages)
        reads_in = n_in * (EXP["read_identity"] * tok("read_identity") + EXP["read_revision"] * tok("read_revision") + EXP["read_decision"] * tok("read_decision"))
        tgt_in = n_in * EXP["targeted"] * tok("read_field_context") if x else 0
        p90_est = disc("p90") + (DOC_CAP - n_in) * tok("read_identity", "p90")
        secs = sum((lat("discover_region") if (roi and p["size"] == "drawing_sheet") else lat("discover_page")) for p in pages) + n_in * (EXP["read_identity"] * lat("read_identity") + EXP["read_revision"] * lat("read_revision") + EXP["read_decision"] * lat("read_decision")) + (n_in * EXP["targeted"] * lat("read_field_context") if x else 0)
        per_arm[arm] = {"expected_requests": round(req, 2), "cap_requests_durable": DOC_CAP, "reader_per_reading_constant": READER_PER_READING,
                        "expected_input_tokens": round(disc() + reads_in + tgt_in), "p90_based_input_tokens_ESTIMATE": round(p90_est),
                        "expected_output_tokens": round(n_in * (out_tok("discover_page") + out_tok("read_identity") + out_tok("read_revision")) + (n_in * EXP["targeted"] * out_tok("read_field_context") if x else 0)),
                        "expected_seconds_sequential": round(secs)}
        per_project[ep][arm] += req
        demand_exp[(arm, f["doc_key"])] = req
        demand_worst[(arm, f["doc_key"])] = DOC_CAP
        seconds_exp[arm] += secs
        for k in ("expected_requests", "expected_input_tokens", "p90_based_input_tokens_ESTIMATE", "expected_output_tokens", "expected_seconds_sequential"):
            totals[arm][k] += per_arm[arm][k]
        totals[arm]["cap_requests_durable"] += DOC_CAP
    rows.append({"doc": f["doc_key"], "ep": ep, "role": f["role"], "pages_in_scope": n_in, "pages_beyond_scope": n_beyond,
                 "page_classes": [(p["page"], p["size"], p["rotation"], p["text"], p["screen_off_title_block_decision"]) for p in pages], "per_arm": per_arm})
pdf_docs = sum(1 for r in rows if r["pages_in_scope"])
a_expected, a_cap = prev["a_base"]["expected_requests"], prev["a_base"]["cap"]
caps = dict(prev["proposed_caps"])                                    # the R21 proposal, unchanged: expected x 1.35 rounded to 5; NOT approved
core_expected = sum(totals[a]["expected_requests"] for a in ARMS) + a_expected
structural_max = pdf_docs * DOC_CAP * 4 + a_cap
# ---- the schedule, generated from the implemented rule ----------------------------------------------------------------------
largest = max(projects, key=lambda ep: len(projects[ep]))
sims = {}
for name, dem in (("worst_case_demand", demand_worst), ("expected_demand", demand_exp)):
    for a_name, a_usage in (("A_aged_out", {}), ("A_cap_spent_on_the_largest_project_at_start", {largest: a_cap})):
        s = schedule_sim.simulate({ep: list(v) for ep, v in projects.items()}, ARMS, dem, limit=DAY, cap=DOC_CAP, a_usage=a_usage, start=0.0, step=3600.0)
        sims[f"{name}/{a_name}"] = {"complete": s["complete"], "elapsed_hours_to_last_batch_start": s["elapsed_h"], "deferral_events": s["deferrals"],
                                     "requests_sent_in_simulation": round(s["sent_total"], 1), "batches": s["batches"], "unfinished": s["unfinished"]}
# the dry fake-clock example (runner evidence S7): 50 other-track requests seeded for EP-16830 at T0; L1 deferred the project
# (needs 24, capacity 10) and ran EP-17428; at T0 + 24 h + 1 s the resume ran EP-16830 without resetting the durable totals
runner_ev = R / "runner-evidence/RUNNER-INTEGRATION.json"
s7 = json.loads(runner_ev.read_text(encoding="utf-8"))["scenarios"]["S7_deferral"] if runner_ev.exists() else "runner-evidence/RUNNER-INTEGRATION.json not yet produced"
fake = schedule_sim.simulate({"16830": ["six", "one"], "17428": ["two", "txt"]}, ["L1"], {("L1", "six"): 9, ("L1", "one"): 3, ("L1", "two"): 5, ("L1", "txt"): 0},
                             limit=DAY, cap=DOC_CAP, a_usage={"16830": 50}, start=0.0, step=3600.0)
schedule = {"rule_version": "whole-project-reservation-2026-09-30.v4", "implemented_in": "harness-v4/arm_ev.py (worst_case + xtrack2.capacity before each project-arm batch)",
            "rule": "before a project-arm batch: the project's rolling 24 h capacity (60 minus every track's requests in the last 24 h, the A base included) must cover the batch's "
                    "worst case (the remaining durable allowance, 12 minus charged, of every pending PDF); otherwise the project is persisted as deferred for that arm and zero "
                    "requests are sent; a later resume takes deferred projects in declared order (arms in the frozen order, projects by EP, documents in stage order)",
            "simulator": "harness-v4/schedule_sim.py (hourly steps; a batch's requests are charged to the window at its start; arms strictly in order, each arm over all projects before the next)",
            "assumptions": ["each arm's batch for a project sends its whole demand at the batch start (the real batch spreads over its run time, so real windows free up later, never earlier)",
                            "sequential requests at the observed p50 latencies; the run time of a batch is NOT added to the window arithmetic (reported separately)",
                            "no failures, timeouts, tripwire stops or cap refusals; a cap refusal only shortens a batch",
                            "the A base's requests are either aged out (L1 starts >= 24 h after A) or its cap of 8 is spent on the largest project at t = 0"],
            "worst_case_per_project_per_arm": {ep: DOC_CAP * len(v) for ep, v in projects.items()}, "frozen_order": ["A"] + ARMS,
            "simulations": sims, "expected_run_time_hours_sequential_per_arm": {a: round(seconds_exp[a] / 3600, 2) for a in ARMS},
            "fake_clock_example": {"dry_runner_evidence_S7": s7, "same_scenario_in_the_simulator": {"complete": fake["complete"], "batches": fake["batches"], "deferral_events": fake["deferrals"]}},
            "note": "elapsed hours are to the START of the last batch; add that batch's run time; nothing here is a completion guarantee",
            "pairs_first": prev["schedule"]["pairs_first"], "incomplete_pairs": prev["schedule"]["incomplete_pairs"],
            "r21_table_correction": "R21 reported 'worst case 3 days / expected 2 days' from a rounded rule of thumb; the simulated figures above replace them"}
budget = {"price": "UNKNOWN: no dollar amount; no cost guarantee",
          "three_request_figures": {"expected_workload_requests": round(core_expected), "proposed_authorized_maximum_requests_IF_APPROVED": sum(caps.values()),
                                    "uncapped_structural_maximum_requests": structural_max, "note": "688 is NOT approved by this package; 509 is an expectation under the stated assumptions; 1,256 is 12 x 26 PDFs x 4 arms + A's 8"},
          "core_expected_input_tokens_incl_cached": round(sum(totals[a]["expected_input_tokens"] for a in ARMS) + a_expected * tok("read_submittal_form")),
          "core_p90_based_input_tokens_ESTIMATE": round(sum(totals[a]["p90_based_input_tokens_ESTIMATE"] for a in ARMS)),
          "p90_label": "an ESTIMATE (p90 of the observed per-task input incl. cached, times the counts), not an upper bound",
          "core_expected_output_tokens": round(sum(totals[a]["expected_output_tokens"] for a in ARMS)),
          "escalations": "EV1 makes none; the cap of 2 per document stays declared", "retries": prev["budget"]["retries"], "timeouts_observed": prev["budget"]["timeouts_observed"],
          "offline_replays": "0 requests", "completion": "a cap below the worst case means arms may stop with documents not attempted; those documents enter the all-planned comparison as budget stops; no completion guarantee"}
out = {"version": "r22-workload-2026-09-30.v2", "replaces": "review21/workload/R21-WORKLOAD.json (same sample, stage, rates and assumptions; schedule generated; labels corrected)",
       "stage_files": len(stage), "pdf_documents": pdf_docs, "pages_total": sum(f["pages"] or 0 for f in stage), "pages_in_scope": sum(r["pages_in_scope"] for r in rows),
       "pages_beyond_scope": sum(r["pages_beyond_scope"] for r in rows), "assumptions": prev["assumptions"], "per_document": rows,
       "per_project": {ep: {a: round(v, 1) for a, v in arms.items()} for ep, arms in per_project.items()}, "per_arm_totals": {a: {k: round(v, 1) for k, v in t.items()} for a, t in totals.items()},
       "a_base": {"expected_requests": a_expected, "cap": a_cap}, "schedule": schedule, "proposed_caps": {"caps": caps, "status": "PROPOSED, NOT APPROVED", "total": sum(caps.values())}, "budget": budget}
(R / "workload").mkdir(exist_ok=True)
(R / "workload/R22-WORKLOAD.json").write_text(json.dumps(out, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
print("pdf docs", pdf_docs, "| expected", budget["three_request_figures"], "| caps", caps)
for k, v in sims.items():
    print(k, "complete", v["complete"], "elapsed h", v["elapsed_hours_to_last_batch_start"], "deferrals", v["deferral_events"], "sent", v["requests_sent_in_simulation"])
print("run time h per arm (sequential, p50)", schedule["expected_run_time_hours_sequential_per_arm"])
